// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY_2mfKV9M8xgMMBJ3Y8pQPS37AOOJmRE',
    appId: '1:1013851184422:web:c0038858f774ab9787f5e7',
    messagingSenderId: '1013851184422',
    projectId: 'shutterduo-ec088',
    authDomain: 'shutterduo-ec088.firebaseapp.com',
    databaseURL: 'https://shutterduo-ec088-default-rtdb.firebaseio.com',
    storageBucket: 'shutterduo-ec088.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY_2mfKV9M8xgMMBJ3Y8pQPS37AOOJmRE',
    appId: '1:1013851184422:android:c0038858f774ab9787f5e7',
    messagingSenderId: '1013851184422',
    projectId: 'shutterduo-ec088',
    databaseURL: 'https://shutterduo-ec088-default-rtdb.firebaseio.com',
    storageBucket: 'shutterduo-ec088.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdvB7LG4sggKrfP1JofGNqvnS-zor1rrE',
    appId: '1:1013851184422:ios:5ec67c137271b65487f5e7',
    messagingSenderId: '1013851184422',
    projectId: 'shutterduo-ec088',
    databaseURL: 'https://shutterduo-ec088-default-rtdb.firebaseio.com',
    storageBucket: 'shutterduo-ec088.appspot.com',
    iosBundleId: 'com.makeitsimple.wePlan',
  );
}
